cash_flow/urls.py
from django.urls import path
from . import views

app_name = 'cash_flow'

urlpatterns = [
    path('', views.home, name='home'),
    path('flows/', views.flows, name='flows'),
    path('flows/search/', views.search_date, name='search_date'),
    path('flows/download_csv/', views.download_csv, name='download_csv'),
    path('flows/relatorio/<str:date>', views.relatorio, name='relatorio'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cash_flow.urls')),
    path('user/', include('users.urls'))
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

cash_flow/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class RegisterModel(models.Model):
    class Meta:
        verbose_name = 'Registro de caixa'
        verbose_name_plural = 'Registros'

    nature_dict = {
        'entry': 'Entrada',
        'output': 'Saida'
    }

    type_dict = {
        'cc': 'Cartão de Crédito',
        'cd': 'Cartão de Débito',
        'din': 'Dinheiro',
        'pix': 'Pix'
    }

    description = models.CharField(max_length=150, blank=False)
    nature = models.CharField(max_length=8, choices=nature_dict, blank=False, default=nature_dict['entry'])
    type_cash = models.CharField(max_length=8, choices=type_dict, blank=True)
    value = models.CharField(max_length=10, blank=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.description

users/models.py
from django.db import models

# Create your models here.

cash_flow/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .form import RegisterFlows
from django.contrib import messages
from .models import RegisterModel
from utils.getdate import getdatesystem, parse_data
from utils.pagination import make_pagination
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
import csv
import datetime


@login_required(login_url='users:login', redirect_field_name='next')
def home(request):
    if request.POST:
        form = RegisterFlows(request.POST)
    else:
        form = RegisterFlows()

    if form.is_valid():
        register = form.save(commit=False)
        register.user = request.user
        register.save()
        messages.success(request, 'Registro salvo com sucesso')
        return redirect(reverse('cash_flow:home'))


    context = {
        'title': 'Home',
        'form': form,
        'button_txt': 'Enviar'
    }

    return render(request, 'cash_flow/pages/home.html', context)

@login_required(login_url='users:login', redirect_field_name='next')
def flows(request):
    actually_data = getdatesystem()

    flows = RegisterModel.objects.filter(created_at__icontains=actually_data).order_by('-created_at')

    page_obj = make_pagination(request, flows)

    context = {
        'flows': page_obj,
        'date': actually_data,
        'title': 'Fluxos',
    }

    return render(request, 'cash_flow/pages/flows.html', context)

@login_required(login_url='users:login', redirect_field_name='next')
def search_date(request):
    search_term = request.GET.get('date')

    if not search_term:
        raise Http404()
    
    flows = RegisterModel.objects.filter(created_at__icontains=search_term).order_by('-created_at')

    page_obj = make_pagination(request, flows)

    context = {
        'flows': page_obj,
        'date': search_term
    }

    return render(request, 'cash_flow/pages/flows.html', context)

@login_required(login_url='users:login', redirect_field_name='next')
def relatorio(request, date):
    flows = RegisterModel.objects.filter(created_at__icontains=date)

    soma_entry = 0.0
    soma_output = 0.0
    soma_cc = 0.0
    soma_cd = 0.0
    soma_din = 0.0
    soma_pix = 0.0
    for flow in flows:
        flow.value = float(flow.value.replace(',', '.'))
        if flow.nature == 'entry':
            soma_entry += flow.value
        elif flow.nature == 'output':
            soma_output += flow.value

        if flow.type_cash == 'cc':
            soma_cc += flow.value
        elif flow.type_cash == 'cd':
            soma_cd += flow.value
        elif flow.type_cash == 'din':
            soma_din += flow.value
        elif flow.type_cash == 'pix':
            soma_pix += flow.value


    dif_total = soma_entry - soma_output

    context = {
        'soma_entry': f'{soma_entry:.2f}',
        'soma_output': f'{soma_output:.2f}',
        'dif_total': f'{dif_total:.2f}',
        'soma_cc': f'{soma_cc:.2f}',
        'soma_cd': f'{soma_cd:.2f}',
        'soma_din': f'{soma_din:.2f}',
        'soma_pix': f'{soma_pix:.2f}'
    }

    return render(request, 'cash_flow/pages/relatorio.html', context)
    
@login_required(login_url='users:login', redirect_field_name='next')
def download_csv(request):
    if not request.POST:
        raise Http404()
    
    response = HttpResponse(content_type='text/csv; charset=utf-8')
    response['Content-Disposition'] = 'attachment; filename="Relatório.csv"'

    writer = csv.writer(response)

    writer.writerow(['Data', 'Descrição', 'Natureza', 'Tipo', 'Valor'])

    try:
        date = parse_data(request.POST.get('date'))
    except:
        date = request.POST.get('date')

    flows = RegisterModel.objects.filter(created_at__icontains=date).order_by('-created_at')

    nature = ''
    type_cash = ''
    for flow in flows:
        date = datetime.datetime.fromisoformat(str(flow.created_at))
        date_format = date.strftime('%d/%m/%Y')
        if flow.nature == 'entry':
            nature = 'Entrada'
        elif flow.nature == 'output':
            nature = 'Saida'

        if flow.type_cash == 'din':
            type_cash = 'Dinheiro'
        elif flow.type_cash == 'cc':
            type_cash = 'Cartão de crédito'
        elif flow.type_cash == 'cd':
            type_cash = 'Cartão de débito'
        elif flow.type_cash == 'pix':
            type_cash = 'Pix'
        else:
            type_cash = '-'

        writer.writerow([date_format, flow.description, nature, type_cash, flow.value])

    return response  

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .form import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def login_view(request):
    if request.POST:
        form = LoginForm(request.POST)
    else:
        form = LoginForm()
    
    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', '')
        )

        if authenticated_user is not None:
            messages.success(request, 'Logado com sucesso')
            login(request, authenticated_user)
            return redirect(reverse('cash_flow:home'))
        else:
            messages.error(request, 'Seu usuário ou senha estão incorretas')
            
    context = {
        'form': form,
        'button_txt': 'Entrar'
    }

    return render(request, 'users/login.html', context)

@login_required(login_url='users:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return redirect(reverse('users:login'))
    
    if request.POST.get('username') != request.user.username:
        return redirect(reverse('users:login'))
    
    logout(request)
    return redirect(reverse('users:login'))

cash_flow/templates/cash_flow/pages/flows.html
{% extends "global/base.html" %}

{% block content %}
    <h1 class="flow-title">Registros Salvo</h1>
    {% include "global/partials/search.html" %}
    {% if flows %}
        {% include "global/partials/table.html" %}
        <div class="center">
            <h4>Legenda:</h4>
            <ul>
                <li><span>cc</span>: Cartão de crédito</li>
                <li><span>cd</span>: Cartão de débito</li>
                <li><span>din</span>: Dinheiro</li>
                <li><span>pix</span>: Pix</li>
            </ul>

            <p class="geral">Para ver o panorama geral <a href="{% url "cash_flow:relatorio" date %}">Clique aqui</a></p>

            <form class="form-download" action="{% url "cash_flow:download_csv" %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="date" value="{{ date }}">
                <input type="submit" value="Exportar CSV">
            </form>
        </div>
    {% else %}
        <h2 class="flow-ter">Ainda não há registro cadastrado!</h2>
    {% endif %}
    
{% endblock content %}

cash_flow/templates/cash_flow/pages/home.html
{% extends "global/base.html" %}

{% block content %}
    <div class="container-form">
        <h1>Registre Seu fluxo de caixa aqui</h1>
        {% include "global/partials/form.html" %}
    </div>
{% endblock content %}

cash_flow/templates/cash_flow/pages/relatorio.html
{% extends "global/base.html" %}

{% block content %}
    <h2 class="title">Relatorio de fluxo</h2>
    <div class="container-card">
        <h3>Relatorio Geral</h3>
        <div class="card">
            <p><span class="bold">Entrada:</span> <span>R$ {{soma_entry}}</span></p>
        </div>
        <div class="card">
            <p><span class="bold">Saida:</span> <span>R$ {{soma_output}}</span></p>
        </div>
        <div class="card">
            <p><span class="bold">Receita Final:</span> <span>R$ {{dif_total}}</span></p>
        </div>
    </div>

    <div class="container-card">
        <h3>Relatorio por tipo de pagamento</h3>
        <div class="card">
            <p><span class="bold">Cartão de crédito:</span> <span>R$ {{ soma_cc }}</span></p>
        </div>
        <div class="card">
            <p><span class="bold">Cartão de débito:</span> <span>R$ {{ soma_cd }}</span></p>
        </div>
        <div class="card">
            <p><span class="bold">Dinheiro:</span> <span>R$ {{ soma_din }}</span></p>
        </div>
        <div class="card">
            <p><span class="bold">Pix:</span> <span>R$ {{ soma_pix }}</span></p>
        </div>
    </div> 
{% endblock content %}

users/templates/users/login.html
{% extends "global/base.html" %}

{% block content %}
    <div class="container-form">
        <h1>Faça Seu login Aqui</h1>
        {% if not user.username %}
            {% include "global/partials/form.html" %}
        {% else %}
            <p>Você esta logado com <span class="bold">{{ user.username }}</span></p>
        {% endif %}
        
    </div>
{% endblock content %}